### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#101]
In the early days we broke everything at least 2 or 3 times because we forgot or missed stuff. We need to write lots of detailed tests both unit and functional and simulate many conditions to ensure new releases won't break anything. Especially the auto-update logic.
It would be a lot more catastrophic now. I actually think we still have like 100 probes stuck forever waiting for the container to get rebooted by someone.
Let's ensure this never happens again

**Comment by alexey-yarmosh** [comment]
Sounds valid, the only thing is that we should solve https://github.com/jsdelivr/globalping/issues/262 first, as the same problem will occur in globalping-probe repo.
