### ISSUE TITLE
Setup even better release flow

### ISSUE THREAD

**Issue by zarianec** [jsdelivr/globalping-probe#12]
The idea is to create a Workflow that can be triggered manually from the GitHub UI. This workflow will use semantic-release to:

1. bump package version and update the `package.json` file
2. generate release notes
3. publish GH release

TODO:
- [x] #9 
- [x] add manual GH Workflow that will publish new releases
- [x] set up semantic-release
- [x] set up commit-lint and add git hook

**Comment by zarianec** [comment]
This must be done before #11 because the version in `package.json` is out of sync with releases on GH.

**Comment by jimaek** [comment]
Maybe we should not include the version in package.json? You can get the version from `.git` thats how jsDelivr does it.
e.g. https://www.npmjs.com/package/get-git-version

Aso note that the this better flow will heavily rely on the new auto-update logic
