### ISSUE TITLE
Minimize amount of logs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#122]
Docker doesnt rotate them by default. So to avoid stability issues we need to make sure we generate as little as possible. 

Current example output attached

[logs.txt](https://github.com/jsdelivr/globalping-probe/files/10993840/logs.txt)

**Comment by jimaek** [comment]
Maybe dont even generate any unless an env var is passed?

**Comment by alexey-yarmosh** [comment]
We should also update the docker configuration, so that problem will not be actual for new probes. `"log-driver": "local"` seems to do the trick, but need to dive deeper.

**Comment by jimaek** [comment]
added driver local parameter to readme
