### ISSUE TITLE
Increase reconnect timeouts

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-probe#179]
I suggest using a base of `2000ms` with a `randomizationFactor: 0.75`, effectively making the initial reconnect time 500 - 3500ms. `reconnectionDelayMax` for repeated attempts can be `8000ms`.

**Comment by alexey-yarmosh** [comment]
> I suggest using a base of 2000ms with a randomizationFactor: 0.75, effectively making the initial reconnect time 500 - 3500ms. 

3500ms max value = 2000 + (1 * 0.75 * 2000) as I understand, but where does 500ms min come from?

> reconnectionDelayMax for repeated attempts can be 8000ms.

Do you mean some backoff with 8000ms max should be applied?

**Comment by MartinKolarik** [comment]
IIRC the factor goes either way so 2000 - 1500 = 500. And exponential back off is built in, just adjust the max delay via the option.
