### ISSUE TITLE
Don't rely on GitHub directly for updates

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-probe#189]
GitHub doesn't support IPv6 so probes in IPv6-only networks won't be able to reach it.

**Comment by MartinKolarik** [comment]
Here's a question of how we do this as well. We *could* use https://data.jsdelivr.com/v1/packages/gh/jsdelivr/globalping-probe if we add AAAA for the data domain (www already has it), and Bunny supports it, so it should be fine.

However, render.com doesn't support IPv6 yet, so if we ever need to remove the CDN, it suddenly creates a problem. Custom endpoint on our CDN is also an option if we can guarantee all providers support IPv6 (which we should), or there's an option of something entirely custom outside jsDelivr.

**Comment by jimaek** [comment]
I think using an ipv6 CDN on top of data.jsd is fine, using it without it is a no go either way since their bandwidth is super expensive

**Comment by jimaek** [comment]
btw we dont need to add anything, data.jsd is already ipv6 enabled

**Comment by MartinKolarik** [comment]
> using it without it is a no go either way since their bandwidth is super expensive

It is no go long-term but short-term if Bunny has issues, our first resort might be removing it for a day. We have done it a couple of times already. We can go this way, just need to be more careful when making changes to consider this aspect.

> btw we dont need to add anything, data.jsd is already ipv6 enabled

Indeed.

**Comment by MartinKolarik** [comment]
Adding "on hold" until we resolve the IPv6 DNS issue in the US.

**Comment by MartinKolarik** [comment]
Just a note here that if we only need the latest version, https://data.jsdelivr.com/v1/packages/gh/jsdelivr/globalping-probe/resolved is an easier way to get it.

**Comment by MartinKolarik** [comment]
This is trickier than I realized at first because after we get the version (from data.jsd) we need to get the URL of the actual release and then download it, and that's another GH API call - but one that can't be replaced by our own API. Custom CDN option seems like the best way to handle this?

**Comment by jimaek** [comment]
But what do we proxy with the CDN? The GitHub API directly?

**Comment by MartinKolarik** [comment]
We need two things:
1. https://api.github.com/repos/jsdelivr/globalping-probe/releases/latest - gives us version / link to the release
2. https://github.com/jsdelivr/globalping-probe/releases/download/v0.29.0/globalping-probe.bundle.tar.gz - this is the asset URL

They are at different domains, so I'd do this:
1. Use data API to get the version.
2. Construct the link manually and get cdn.jsdelivr.net/globalping-probe/{{version}}/globalping-probe.bundle.tar.gz (we have a setup like this for musescore/atlas already)

**Comment by jimaek** [comment]
How about adding a failover to those domains? e.g. if cdn.jsdelivr.net is not available, try fastly.jsdelivr.net

**Comment by MartinKolarik** [comment]
I could do it for `.net`, but we don't have another domain for `data` (and that's also queried in multiple places, so could become messy). Also, if either of the services is down, it doesn't matter to the probe, it'll update later. Only possible issue is if the domain got blocked in some country I guess.

**Comment by jimaek** [comment]
Lets do it for .net just in case

**Comment by MartinKolarik** [comment]
Ok, updated.
