### ISSUE TITLE
Fix handling of AAAA records

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-probe#190]
Currently, DNS lookups fail with:

```
Error: IPv6 not supported
    at isIpPrivate (file:///app/dist/lib/private-ip.js:27:15)
```

**Comment by SukkaW** [comment]
The handling of `isIpPrivate` was removed in https://github.com/jsdelivr/globalping-probe/pull/165, and here I quote:

> The failing tests were caused by one of the IPv6 ranges. I'm not sure which one and why exactly, but since we don't support IPv6 at all yet, I deleted those rules for now.

https://github.com/jsdelivr/globalping/pull/410#issuecomment-1656850969
