### ISSUE TITLE
China container proxy

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#198]
Need to investigate this https://doc.nju.edu.cn/books/35f4a/page/ghcr proxy reported here https://github.com/jsdelivr/globalping-probe/issues/30  and if we can somehow automate the process of choosing the best registry based on the user's location.

**Comment by jimaek** [comment]
@cherinyy hey, do you know if Cloudflare works ok in China? We could proxy cache our registry through Cloudflare, but I am not sure what their performance is in China.

**Comment by jimaek** [comment]
@SukkaW Maybe you can help too?

**Comment by cherinyy** [comment]
> hey, do you know if Cloudflare works ok in China? We could proxy cache our registry through Cloudflare, but I am not sure what their performance is in China.

China Telecom and China Unicom will connect to the Cloudflare Los Angeles or San Jose nodes, and China Mobile will connect to the Hong Kong node.

Network performance is average, but usable.

![image](https://github.com/jsdelivr/globalping-probe/assets/9050713/8f219bb2-a763-483b-989c-c2fb8942ca76)

[speed-results-1710678951.csv](https://github.com/jsdelivr/globalping-probe/files/14627400/speed-results-1710678951.csv)

**Comment by jimaek** [comment]
That does seem a lot better than anything else that can be used globally

**Comment by jimaek** [comment]
Can you also test these different registries and let me know which is the fastest and most stable?

```
Docker
docker pull globalping/globalping-probe

Github
docker pull ghcr.io/jsdelivr/globalping-probe

Google
docker pull mirror.gcr.io/globalping/globalping-probe
```

**Comment by cherinyy** [comment]
Docker
https://github.com/jsdelivr/globalping-probe/assets/9050713/835a6f90-1d0b-4414-a96a-fa96be2fb990

GitHub
https://github.com/jsdelivr/globalping-probe/assets/9050713/1d180421-7d34-4f2c-85e9-f1a33b4c57bb

Google
https://github.com/jsdelivr/globalping-probe/assets/9050713/0d01a220-6f42-4335-ae2b-653baeb8bef4

So it's obviously Docker Hub.
