### ISSUE TITLE
DNS command - Real time update 

### ISSUE THREAD

**Issue by zarianec** [jsdelivr/globalping-probe#2]
DNS command measures resolving performance and collects resolved output.
See https://github.com/jsdelivr/globalping/issues/6 for command options

A possible command that can be used to resolve target:

```
dig -4 +time=1 +tries=2 +edns +stats @1.1.1.1 MX google.com
```

dig output is pretty complex and may change significantly depending on the params so we should avoid parsing it manually.

Need to check this package https://www.npmjs.com/package/node-dig-dns and see if it can parse the output with the params we need.

**Comment by patrykcieszkowski** [comment]
reopening, as a reminder we'll have to replace the package for IRL results after MVP release.

**Comment by zarianec** [comment]
Could you also add 'dnsutil' package in dockerfile because dns command currently doesn't work.
