### ISSUE TITLE
Define hardware probe on old devices

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping-probe#206]
`GP_HOST_HW` and `GP_HOST_DEVICE` variables are not available on hw probes right now, and when it goes live only new devices will have it, old ones need manual upgrade.

To detect hw probes when vars are not provided I think we can use some of the OS values. Like node.js `os.arch()`, `os.cpus()` model, `os.platform()`, or a combination of them.

**Comment by jimaek** [comment]
Need to run those commands on a real device to see the output. I think you had one handy in dev mode @MartinKolarik

**Comment by MartinKolarik** [comment]
See https://github.com/jsdelivr/globalping-hwprobe/issues/37#issuecomment-2002039986, I think we could go with the combination of following:
 - 4 cores "ARMv7 Processor rev 5 (v7l)"
 - RAM < 550 MB
 - hostname matches "globalping-probe-" followed by 4 characters (see https://github.com/jsdelivr/globalping-hwprobe/blob/40d466dd6ad1468615f800ac1f50d54ab8b101a3/meta-jsdelivr/recipes-jsdelivr/jsdelivr-service/files/firstboot.sh#L4)

**Comment by jimaek** [comment]
Cant we just detect the linux distro name? It should be super unique since its IoT specific

**Comment by MartinKolarik** [comment]
Node doesn't say more than "Linux" but if it's included in the output of `uname -a` or a similar command that might work as well.

**Comment by MartinKolarik** [comment]
> Node doesn't say more than "Linux" but if it's included in the output of uname -a or a similar command that might work as well.

That doesn't seem helpful, so I say we go with the HW check: https://github.com/jsdelivr/globalping-probe/issues/206#issuecomment-2002041269
