### ISSUE TITLE
WARNING: PROBE FIRMWARE OUTDATED, PLEASE UPDATE

### ISSUE THREAD

**Issue by skapytek** [jsdelivr/globalping-probe#236]
Probe wont update.
Already tried reflashing.

Current version 0.31.1
Latest version 0.31.1
[2024-06-03T21:35:36.495Z] Current node.js version v18.14.2
[2024-06-03T21:35:36.526Z] Wanted node.js version v20.13.0
Hardware probe detected. Not updating.

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: PROBE FIRMWARE OUTDATED, PLEASE UPDATE     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Current probe firmware is out of date and we couldn't update it automatically.
Please update it manually using the guide from GitHub:
https://github.com/jsdelivr/globalping-hwprobe#download-the-latest-firmware

[2024-06-03 21:35:42] [INFO] [general] Start probe version 0.31.1 in a production mode.

**Comment by MartinKolarik** [comment]
Hey, sorry for the confusion. We didn't make a release with the latest FW updates yet, so when you reflashed to 1.4 (the latest public release), it was still detected as outdated.

The good news is:
 - the probe works fine as it is right now,
 - soon, we'll release a new version of the FW, which will have the ability to auto-update its node.js version, so after a single manual reflash, this won't repeat in the future.

I'll keep the issue open until the updated FW is released in case anyone else comes across this.

**Comment by skapytek** [comment]
Thanks for the clarification. Any ETA for the release?

**Comment by jimaek** [comment]
Replied in the firmware repo
