### ISSUE TITLE
status: failed for IPv6 ping

### ISSUE THREAD

**Issue by jason5ng32** [jsdelivr/globalping-probe#241]
I tried to ping a v6 IP address on globalping, datas were returned correctly, but the status returned failed.
Would you consider supporting Ping6 command or make Ping command work correctly for v6 address?
Thanks.

**Comment by jason5ng32** [comment]
Great to know this issue has been fixed, is it possible to test on globalping website lately?

**Comment by MartinKolarik** [comment]
Not yet, we'll comment here when we make a release that includes the fix (should be this week). After that, the change will be live in 30 minutes.
