### ISSUE TITLE
Add dashboard link

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping-probe#251]
Let's add a message and link about the dashboard in the probe logs during boot.

**Comment by MartinKolarik** [comment]
If we do this, it'd be good to check if the probe is already adopted or not first.

**Comment by alexey-yarmosh** [comment]
Ideally `isAdopted` field should be added to the `Probe` object. But I am not sure if that change should be added just to support conditional log message. Maybe we can show the message always? Or smth like that may be an alternative:
https://github.com/jsdelivr/globalping/compare/dashboard-link?expand=1

@MartinKolarik wdyt?

**Comment by MartinKolarik** [comment]
> https://github.com/jsdelivr/globalping/compare/dashboard-link?expand=1

This seems fine but I'd add it as a new event, no need to combine it with the location data.
