### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Ernst2020** [jsdelivr/globalping-probe#257]
Hi,

Two questions:

1. Is there a way to make a distinction between hardware and software probes? 

2. Is logging on a hardware probe in RAM? If not, the SD card will have low life expectancy.

Regards,

Ernst

**Comment by jimaek** [comment]
1. Where exactly? We do have a way to differentiate them on the API level thanks to env vars that hw probes set
2. Everything is in RAM, the sd card is read-only and is barely touched. We work with an experienced IoT developer and of course we thought of such issues. And the OS itself https://www.yoctoproject.org is also designed for such use-cases, which we compile specifically for our hardware, software and use-case. It's part of what makes the probe secure, not only we don't open any ports, we don't even include most of the unrelated software that could potentially be abused.
3. 
For example here is the relevent disk config https://github.com/jsdelivr/globalping-hwprobe/blob/master/meta-jsdelivr/recipes-jsdelivr/jsdelivr-scripts/files/jsdelivr-startWorld.sh

**Comment by Ernst2020** [comment]
Ok. Thanks! 

1. Will need to explore the API more.
2. Excellent. Some users were worried about this.

**Comment by Ernst2020** [comment]
Had a look at the API docs at https://globalping.io/docs/api.globalping.io#overview

No mention of env_vars?

**Comment by jimaek** [comment]
Sorry I meant an internal API. Meaning we have this information but I wasn't sure where you wanted to see it or how to use it. So that we could potentially add it

**Comment by Ernst2020** [comment]
Ah. I wanted to see how many of the shipped HW probes are currently installed since only 27 new probes appeared since October 5th.
Can you easily generate an overview of which of the probes in NL are hardware based? And email me?

**Comment by MartinKolarik** [comment]
We only have that information for adopted probes, and there are 31 HW adopted probes in NL at the moment. I suspect most of them are related to the recent shipment.

**Comment by alexey-yarmosh** [comment]
If I am not missing something, every probe returns hw status to the API. There are 140 NL probes currently, 35 of them are hardware.

**Comment by Ernst2020** [comment]
Still the **internal** API is meant I guess?

**Comment by alexey-yarmosh** [comment]
yes(

**Comment by Ernst2020** [comment]
Any plans to add the distinction to externally visible data?

**Comment by MartinKolarik** [comment]
> If I am not missing something, every probe returns hw status to the API. There are 140 NL probes currently, 35 of them are hardware.

Ah, we're returning the property only if it's true, slightly confusing 😄

**Comment by MartinKolarik** [comment]
> Any plans to add the distinction to externally visible data?

Generally speaking, the goal is to include data that has a clear use case and value to most users. I don't really see that here.

**Comment by jimaek** [comment]
We could make the probe type public as part of this page https://github.com/jsdelivr/www.jsdelivr.com/issues/689
I'll make a note
