### ISSUE TITLE
Disconnects in dashboard

### ISSUE THREAD

**Issue by Ernst2020** [jsdelivr/globalping-probe#259]
A number of users in The Netherlands report regular disconnected probes as reported in their dashboard. I also had 3 disconnected probes of which two had no IP change or downtime.

People report that deleting the probe and adopting it again works fine.

It looks as if there is either a bug somewhere or that the connect/disconnect mechanism is a bit too sensitive.

Any suggestions?

**Comment by MartinKolarik** [comment]
We fixed an issue that caused this today morning and most of the adopted probes are reported as online again. I also randomly checked a few of those that remained offline and those are indeed not connected.

**Comment by jimaek** [comment]
Does the fix address this as well?



> This may be related to [jsdelivr/globalping#546](https://github.com/jsdelivr/globalping/issues/546)

**Comment by MartinKolarik** [comment]
It is not related.

**Comment by MartinKolarik** [comment]
The latest probe update should also address cases where the probe might occasionally disconnect in dual-stack networks behind NAT (typical home setups).
