### ISSUE TITLE
Add OPTIONS as an allowed HTTP Method

### ISSUE THREAD

**Issue by Vittitow** [jsdelivr/globalping-probe#261]
HTTP probes support GET and HEAD today. I can see why POST isn't supported but I don't see a reason why OPTIONS couldn't be supported as it's pretty much equivalent to HEAD. Lots of sites block HEAD requests but allow OPTIONS for browser CORS compatibility.

**Comment by jimaek** [comment]
Hey, I don't see why not, but it would also be helpful to better understand your use case. 
For example are you trying to use HEAD to measure latency and getting blocked?

**Comment by Vittitow** [comment]
Correct, I'm currently using HEAD requests to just measure latency from different geos to try and avoid putting any load on the sites. I'm getting a 403 Forbidden response so technically not completely blocked and it kind of still works for my use case but, I feel it would be better if we could use OPTIONS which would return a 200. Especially in the case of sites that use Cloudflare or any type of WAF for that matter. They can block HEAD requests before it actually makes it to the origin server making the latency measurement inaccurate.

**Comment by alexey-yarmosh** [comment]
Since the `OPTIONS` response may have a body, I am not sure if it should be included in our response. It is not required in that particular case, but looks safe enough to save it in the result, if available. @jimaek wdyt?

**Comment by jimaek** [comment]
Looks like its allowed for OPTIONS to respond with a body and some use-cases might use it, I think we should include it
