### ISSUE TITLE
Reduce container size further or add a China proxy

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#30]
Pulling our container from China was a pain, its super slow. I think there must be ways to reduce the size of our main container even further. If anyone has any ideas lets discuss them.

**Comment by ayuhito** [comment]
https://dockersl.im does seem like an ideal way to optimise the container image more. I might experiment with it to see the difference later.

**Comment by jimaek** [comment]
I've tried it but it wasn't very helpful. Too difficult to automate, too risky as we could break stuff and not notice it and the manual savings were minimal.
But I've also not seen a single Chinese proxy of the Github docker registry.

**Comment by cherinyy** [comment]
Nanjing University provides a cache for the GitHub Container registry.

```
docker run -d --log-driver local --network host --restart=always --name globalping-probe ghcr.nju.edu.cn/jsdelivr/globalping-probe
```

**Comment by jimaek** [comment]
Thank you, I opened a task to look into it
