### ISSUE TITLE
Probes dont reconnect

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#38]
We had an outage where the API crashed hard with 500 errors and it took a few hours to come back online. 
Once it started working no probes re-connected. That's pretty bad, we need to understand why they didn't and correct that for the future

**Comment by patrykcieszkowski** [comment]
@jimaek probes disconnected, because the server requested them to; they didn't freeze - the server might've, but they were kicked out. By default, a server kick event isn't followed by reconnect; with this change, it will attempt to reconnect no matter what the cause of the disconnect was.

I don't think a cronjob would help much here. We can throw a SIGTERM every 24hrs or 7 days as you asked just for a good measure, but that won't affect much in this particular case.

**Comment by jimaek** [comment]
In case of Plan B it doesn't matter why they froze, the problem is that once we have hardware probes it will be impossible for us to intervene. So any bug or random issue could cause another freeze(for another reason) and if the update fails as well we will lose all of those probes for months or even years, until they lose power.

So the question is how do we avoid this from happening again, not because of Redis, but for any other reason we can't predict right now. Basically I am asking your ideas for possible failsafes

**Comment by patrykcieszkowski** [comment]
- lost network connection will cause ping/pong timeout - `disconnect` event will be called, and the handler will reconnect
- missing/wrong probe version will return  `connection_error` event - with **NO RECONNECTION ATTEMPT**. This should be handled by the updater.
- `heap out of memory` error should kill the app - docker `restart=always` flag should restart the container
- the same applies to any random crash - docker should handle the restart

I don't really see a scenario where socket connection would be interrupted with no reconnect at this point. But I'm all implementation of a scheduled restart, just in case. I think 24hrs + random delay should be just about. What do you think?

**Comment by jimaek** [comment]
Yeah I will add a random restart to the hardware probes, that what we control outside the container. But I guess for the software probes we dont control we will rely on updates

**Comment by patrykcieszkowski** [comment]
@jimaek PR #40 takes care of the in-container restart

**Comment by jimaek** [comment]
The issue persists. An API reboot lost all probes

```
Latest version 0.3.0
Start self-update process
Self-update finished
[2022-05-09 10:56:22] [INFO] [24] [general] Start probe version 0.3.0 in a production mode
[2022-05-09 10:56:22] [DEBUG] [24] [general] connection to API established
[2022-05-09 10:56:22] [INFO] [24] [api:connect] connected from (krakow, PL, EU) (lat: 50.0614 long: 19.9366)
[2022-05-09 14:01:16] [DEBUG] [24] [general] disconnected from API. (transport close)
[2022-05-09 14:01:32] [DEBUG] [24] [general] connection to API established
[2022-05-09 14:01:32] [INFO] [24] [api:connect] connected from (krakow, PL, EU) (lat: 50.05 long: 19.95)
[2022-05-09 14:01:59] [DEBUG] [24] [general] disconnected from API. (transport close)

```
