### ISSUE TITLE
error handling on stdout - pipe buffer

### ISSUE THREAD

**Issue by patrykcieszkowski** [jsdelivr/globalping-probe#59]
Pipe buffer was delaying progress updates, and on some commands - prevented them from appearing at all. I ended up using `script` cmd to disable it, but it merges `stdout` and `stderr` outputs together. We have to either find a better solution or to somehow distinguish between the desired output and the error.

**Comment by patrykcieszkowski** [comment]
We could print errors to a log file, and read them directly from the file. This would stop errors from appearing in `stdout`.

```
ping -4 -c 3 -i 0.2 -w 15 -n br.debian.org 2>/tmp/errorlog
```

Of course, every measurement would need to have its own errorlog file.

**Comment by patrykcieszkowski** [comment]
Here's what I found, and I actually don't understand why that is:

If from within `stdout` handler, you call `cmd.stderr?.emit('error', data)`, the execa is going to fail and will report an error. However, the error won't be reported under `stderr` value, but under `stdout`.

**Comment by patrykcieszkowski** [comment]
> Alternativelly, we could attach a prefix to stderr and distinguish errors from the actual output that way:

As it turns out, when modifying `stderr` input, the result is not always present. It's especially noticible if you run test on multuple probes at once. I don't know why.

**Comment by patrykcieszkowski** [comment]
going back to `unbuffer` seems like the only solution; it captures the exit code, which makes errors resolve as usual.

**Comment by jimaek** [comment]
Ok well let's do it then. Better now than after going live

**Comment by patrykcieszkowski** [comment]
`mtr` always ends with exit code `0` when requested with non-UI output type. Seems like we gonna have to rely on manual handling at some cases.
