### ISSUE TITLE
Docker container self-update

### ISSUE THREAD

**Issue by zarianec** [jsdelivr/globalping-probe#7]
Assume the user will never pull a new Docker container. We must check if it is possible to do auto-updates within a docker container.

Alternatively, we may bundle the app into a single binary and find the solution to swap binaries with new ones. What is the issue here is that we may want to update `ping`, `traceroute`, or `dig` binaries

**Comment by patrykcieszkowski** [comment]
No, not on it's own. We can bundle the container with watchtower in `docker-compose.yml` file.

Alternatively, the Dockerfile could simply export a bash script, which would clone the repo and build it on its own. Then you can include a cronjob and repeat the process whenever you want. But I don't feel like thats an appropriate direction.

**Comment by jimaek** [comment]
docker-compose will not work, our goal is to provide a single container that the user will start and forget about it. 
Binding docker sockets is also not an option. It will introduce security and privacy questions/issues. 

>Alternatively, the Dockerfile could simply export a bash script, which would clone the repo and build it on its own. Then you can include a cronjob and repeat the process whenever you want. But I don't feel like thats an appropriate direction.

Running a cronjob inside the container is an option. But need to understand better what it will do. How will it detect new versions and how it will update the probe, with minimum downtime.

**Comment by jimaek** [comment]
We will ask our users to start the container with `--restart always` parameter anyway.
How about if inside the container we detect a new version of the probe we kill the container from inside. It crashes and gets restarted.
And then on startup we have a script that tries to upgrade the probe if it detects a new version

**Comment by patrykcieszkowski** [comment]
@jimaek normally, you would compile the app during the build, and as an entry command point the `npm start` command.

You can skip the build process, and point to a custom script file which would query the repo, compare the latest available version at the `package.json` file with the current one, and pull the update. Then rebuild and restart the server.

I'm not a fan of that solution, as that would mean the end-user has absolutely no control over whats happening with their device. We could potentially release a botnet update, and it would be forced upon them, without their knowledge; and I'm pretty sure people would be equally sceptical of the forced auto-update feature.

If we really need to utilise that trick, we should release 2 Dockerfiles. One, built per version, as usual and the other with autoupdate feature.

**Comment by patrykcieszkowski** [comment]
> We will ask our users to start the container with `--restart always` parameter anyway. How about if inside the container we detect a new version of the probe we kill the container from inside. It crashes and gets restarted. And then on startup we have a script that tries to upgrade the probe if it detects a new version

`--restart always` doesn't update the container with the newest version

**Comment by jimaek** [comment]
Releasing probes into prod without an auto-update feature guarantees that that half of our probes will be broken in a few months, or we will have to bend ourselves backwards to force compatibility. The vast majority of users will start it and forget about it. There is no reason for anyone

> @jimaek normally, you would compile the app during the build, and as an entry command point the `npm start` command.
> 
> You can skip the build process, and point to a custom script file which would query the repo, compare the latest available version at the `package.json` file with the current one, and pull the update. Then rebuild and restart the server.
> 
> I'm not a fan of that solution, as that would mean the end-user has absolutely no control over whats happening with their device. We could potentially release a botnet update, and it would be forced upon them, without their knowledge; and I'm pretty sure people would be equally sceptical of the forced auto-update feature.
> 
> If we really need to utilise that trick, we should release 2 Dockerfiles. One, built per version, as usual and the other with autoupdate feature.

Releasing probes into prod without an auto-update feature guarantees that that half of our probes will be broken in a few months, or we will have to bend ourselves backwards to force compatibility. The vast majority of users will start it and forget about it. T



> > We will ask our users to start the container with `--restart always` parameter anyway. How about if inside the container we detect a new version of the probe we kill the container from inside. It crashes and gets restarted. And then on startup we have a script that tries to upgrade the probe if it detects a new version
> 
> `--restart always` doesn't update the container with the newest version

I know. The container would just have an update system on startup. The restart always is needed to get the container back up after crashing it from inside to force the update

**Comment by zarianec** [comment]
the idea with `--restart always` sounds good. This is the easiest way to do self-update so far. But we must add update verification logic so we can be sure that the updated executable is built by us.

Maybe later, if we introduce probes ownership and manual verification, we can remove the self-update mechanism and just notify owners that they run outdated probes.

**Comment by jimaek** [comment]
So instead of compiling each version of our probes into a container, we compile each version into a ready-to-run snapshot, including node_modules and everything and upload that to releases https://github.com/jsdelivr/globalping-probe/releases/tag/v0.1.1

Then the docker container would just be a shell that on start downloads the latest release from Github and runs it as is, without a build step. 

After that all we have to do to upgrade a probe is crash the container.

**Comment by zarianec** [comment]
But it doesn't solve the issue with updating the container with outdated shell script 🙂

**Comment by patrykcieszkowski** [comment]
the shell script would be just and updater. Nothing else.

**Comment by jimaek** [comment]
Technically true, but it should be so simple that after a few releases and testing we should come to a version that will simply work for ever. Download release, unpack, start.



> the shell script would be just and updater. Nothing else.
> 
> (update -> build -> start)

No build. The hardware can be too slow. We should build everything in CI and have the client just download archives

**Comment by zarianec** [comment]
What hardware could run docker but couldn't be able to build a typescript project?) Anyway, we must at least check hash sums for downloaded binary. It means that hardware must be able to calculate that hash 🙂

**Comment by jimaek** [comment]
> What hardware could run docker but couldn't be able to build a typescript project?) Anyway, we must at least check hash sums for downloaded binary. It means that hardware must be able to calculate that hash 🙂

It will be able to build it the question is how fast. I want upgrades to have minimal downtimes.

There are fast hash algorithms that shouldn't be too slow too

**Comment by zarianec** [comment]
We used https://www.npmjs.com/package/pkg before to build executable from js code. It worked well for us. Maybe something changed since then and there are better alternatives now.

**Comment by jimaek** [comment]
Something else we would need to have:
- Graceful shutdown. Stop accepting new tests and finish existing ones before crashing the container
- Randomize the upgrade time. We don't want 1000 probes to shutdown and upgrade all at the same time every time we release a new version. Something like a random time within a 3 hour window
