### ISSUE TITLE
Disconnect non-expect probes

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-probe#71]
How about we add a check for the "unbuffer" command in node itself and if its not detected then the probe connects but stays as "NOT READY". This way it wont impact any tests and we will be able to track how many probes are not-updated.
And remove the useless entrypoint code I added

What do you think?

**Comment by patrykcieszkowski** [comment]
That is one way of dealing with this issue. We could also execute `dpkg` from within the node app, and install the missing packages during runtime.

None of these solutions should be running on production though, but for the beta environment - why not.

**Comment by jimaek** [comment]
Ok, lets try your idea. Can you migrate my bash code to node.js? And make it in a way that is easy to later remove. I'm thinking 6 months should be enough for all current probes to get updated.

**Comment by jimaek** [comment]
I think your idea makes sense now, but once we decide to remove the fix we would still need to implement the original idea since otherwise we would have no idea how many probes are still stuck on the old containers. Its possible we will have 2-3 probes without unbuffer randomly breaking tests for people even after a year.

Maybe leave a comment in the code for the fix that when the fix is removed we need to implement the "not ready" thing instead. So that we dont forget about it

**Comment by patrykcieszkowski** [comment]
I've implemented both solutions. We can safely remove the side-loading mechanism when we're ready.
