### ISSUE TITLE
Keep-Alive with repeated HTTP/S requests

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-probe#79]
#77 made me think about a possible related issue with resuing connections, which could, at the very least, mess up the timings. I *think* it doesn't happen at this time but it seems that'll change in a future version of node, so we need to keep track of that: https://github.com/nodejs/node/pull/43522

**Comment by jimaek** [comment]
Cant we just set keep-alive off always? We dont need

**Comment by MartinKolarik** [comment]
That's exactly what we'll need to do.

**Comment by jimaek** [comment]
Your original post sounds like its about tracking and fixing in the future when they break it. I am saying lets just disable it now and forget about it

**Comment by MartinKolarik** [comment]
So we could update the code now but I would still keep the issue open to retest it with the future version.

**Comment by jimaek** [comment]
Ok, lets disable it then
