### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-probe#84]
As described in https://github.com/jsdelivr/globalping-probe/pull/83#discussion_r929064450, the current tests don't seem to cover the relationship between the input and output at all.

For HTTP, we should use nock, which only provides the response if the request is sent as expected - currently, the response will be received regardless of the request.

For other types, similar asserts should be made with sinon mocks, i.e. assert that the executable would be called with correct params.

**Comment by MartinKolarik** [comment]
Example: I delete [this line](https://github.com/jsdelivr/globalping-probe/blob/1a25aa137f0cfa4461fa4bab11eee6fd0ee1b77d/src/command/mtr-command.ts#L49) and the port option isn't used at all. All tests still pass. They shouldn't.

**Comment by patrykcieszkowski** [comment]
Adding a param builder and testing it per every command, should be enough imo.

**Comment by MartinKolarik** [comment]
I suppose it's one of the ways to do it. Just be careful to not change how the command itself is called. E.g. https://github.com/jsdelivr/globalping-probe/blob/ce4fdd5bab1b0e8b4e72d8cd11ef7daf1860d74b/src/command/ping-command.ts#L49, the params need to be an array, you can't contact them to string yourself. But the builder can indeed return an array that you compare in tests.
