### ISSUE TITLE
DNS returns Private IP error on failed TCP query

### ISSUE THREAD

**Issue by patrykcieszkowski** [jsdelivr/globalping-probe#87]
1. Go to demo page
2. Set protocol to `TCP`
3. Set port to `1`
4. Run the test

**Comment by patrykcieszkowski** [comment]
It seems like the issue is caused by the fact the response comes as an error. The fix is relatively simple, but the message contains an IP add of the resolver. A private IP.

```
;; Connection to 192.168.0.49#212(192.168.0.49) for abc.com failed: connection refused.
```

**Comment by MartinKolarik** [comment]
Before we settle on a solution, note that we're exposing that private IP in the success response:

![image](https://user-images.githubusercontent.com/6192491/181255946-7cf3ad18-bde2-4241-aaf5-475700b0c1c7.png)

**Comment by MartinKolarik** [comment]
I believe with @jimaek we agreed the DNS server shouldn't be exposed, so we could maybe replace it with `x.x.x.x` in both cases?

**Comment by patrykcieszkowski** [comment]
@jimaek what do you think?

**Comment by jimaek** [comment]
Yes I think we should replace the private IPs, but only private and make sure it doesn't interfere with real-time results. I think in the past censoring broke the real-time part until we fixed it.
So same logic as the list of resolvers

**Comment by patrykcieszkowski** [comment]
But the question is, do we want to replace all instances of a private IP occurance, or just the resolver field?

**Comment by jimaek** [comment]
Just the resolver. That's what exposes the LAN info.
