### ISSUE TITLE
Empty rawOutputs

### ISSUE THREAD

**Issue by ayuhito** [jsdelivr/globalping-probe#95]
Not sure if this is intended behaviour, but the following result returns an empty rawOutput string: https://api.globalping.io/v1/measurements/EvvUIAcLuAGv1e03
```
{
  "id": "EvvUIAcLuAGv1e03",
  "type": "dns",
  "status": "finished",
  "createdAt": "2022-08-12T12:03:36.705Z",
  "updatedAt": "2022-08-12T12:03:37.295Z",
  "probesCount": 2,
  "results": [
    {
      "probe": {
        "continent": "EU",
        "region": "Eastern Europe",
        "country": "RU",
        "state": null,
        "city": "Moscow",
        "asn": 196682,
        "longitude": 37.6156,
        "latitude": 55.7522,
        "network": "FLP Kochenov Aleksej Vladislavovich",
        "resolvers": [
          "8.8.8.8",
          "8.8.4.4"
        ]
      },
      "result": {
        "rawOutput": ""
      }
    },
    {
      "probe": {
        "continent": "SA",
        "region": "Southern America",
        "country": "CL",
        "state": null,
        "city": "Santiago",
        "asn": 396982,
        "longitude": -70.6483,
        "latitude": -33.4569,
        "network": "Google LLC",
        "resolvers": [
          "private"
        ]
      },
      "result": {
        "rawOutput": "Private IP ranges are not allowed"
      }
    }
  ]
}
```

It does seem like an unhandled error [here](https://github.com/jsdelivr/globalping-probe/blob/d9ad9addb5f697a45a56e9f3e0084e3709251470/src/command/dns-command.ts#L126) and I think it can be confusing to get no explanation why there is no output at all.

I can't reproduce it consistently, but I used port 80, TCP and trace for the example above. I'm aware this shouldn't work at all, but at least the DIG command returns a timeout/connection refused error for this.

**Comment by patrykcieszkowski** [comment]
Interesting. Technically speaking, the only error we throw is `InternalError` instance, and that's handled. I'll have a look.

**Comment by patrykcieszkowski** [comment]
It didn't work ;(

http://api.globalping.io/v1/measurements/ZfDJv4XaNml3wreN

**Comment by patrykcieszkowski** [comment]
It doesn't happen on the probe from the initial bug report. 

http://api.globalping.io/v1/measurements/9XZaW4aGG22MHMI6
